version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Etc/UTC
    labels:
      - dependencies
      - area/ci
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Etc/UTC
    labels:
      - dependencies
    groups:
      all-minor-patch:
        applies-to: version-updates
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: /.github/scripts
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Etc/UTC
    labels:
      - dependencies
      - area/ci
    groups:
      all-minor-patch:
        applies-to: version-updates
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 5

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Etc/UTC
    labels:
      - dependencies
      - area/core
    groups:
      all-minor-patch:
        applies-to: version-updates
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 10
